- name: Clone application repository
  git:
    repo: "https://github.com/Leon-aka-10/DevOps-Stage-4.git"
    dest: "/home/azureuser/DevOps-Stage-4"

- name: Run Docker Compose
  shell: |
    cd /home/azureuser/DevOps-Stage-4
    docker-compose up -d --build
