---
          - name: Install required packages
            apt:
              name:
                - docker.io
                - docker-compose
              state: present
              update_cache: yes

          - name: Start and enable Docker
            systemd:
              name: docker
              state: started
              enabled: yes

          - name: Install Traefik
            shell: |
              docker run -d --name traefik \
                -p 80:80 -p 443:443 \
                -v /var/run/docker.sock:/var/run/docker.sock \
                traefik:v2.9